### ISSUE TITLE
Question: How does "a single translation across all parts" perform compared with "translation predicted for every corresponding part"? 

### ISSUE THREAD

**Issue by andrehuang** [shubhtuls/volumetricPrimitives#1]
Thanks for sharing the code. We are considering using this code for our own project. I noticed that in your code, you actually didn't predict a translation for every part, despite the paper's formula. Intuitively, this shouldn't make a big difference, but have you done experiments to compare them? I would really love to know the results. Thanks!

**Comment by shubhtuls** [comment]
Thanks for the question. First, a clarification: we **do predict a separate translation for each primitive**. The relevant code path that highlights is -
a) The main function [adds the primitive prediction layers](https://github.com/shubhtuls/volumetricPrimitives/blob/master/experiments/cadAutoEncCuboids/primSelTsdfChamfer.lua#L145-L146) to the CNN.
b) A separate [prediction branch is added for each primitive](https://github.com/shubhtuls/volumetricPrimitives/blob/master/modules/primitives.lua#L225-L227).
c) Within each branch, a separate [translation is predicted for each primitive](https://github.com/shubhtuls/volumetricPrimitives/blob/master/modules/primitives.lua#L199).

I think the confusion here stems from [a code comment](https://github.com/shubhtuls/volumetricPrimitives/blob/master/modules/primitives.lua#L199) relevant to some internal unreleased experiments. At some point, we were experimenting with using different kinds of parts (e.g. cylinders and cuboids), but were predicting a common translation across these choices (hence the comment).

Hope this clarifies things.

**Comment by andrehuang** [comment]
Thanks. This does help!

**Comment by abhikhanna30** [comment]
Hi Shubham,
Can you comment more on the tsdf chamfer and symmetry loss that's there in the code and how do they correlate with coverage and consistency losses in the paper.
Thanks.

**Comment by shubhtuls** [comment]
Hi @abhikhanna30 ,
Apologies for the inconsistencies in names of terms between the code and in the paper. The paper describes 2 losses (Consistency(Sec 3.2.3) and Coverage (Sec 3.2.2)). In the code, these correspond to the ‘errChamfer’ and ‘errTsdf’ respectively.

The symmetry loss samples points on the predicted cuboids, reflects them, and then expects the resulting distance field to be 0 on the reflected points. It was not talked about in the paper as practically speaking, It is not really important and one gets essentially similar results if you turn it off (by passing an argument 'symLossWt=0’ when training). Unfortunately, it has persisted in the code for legacy reasons.

**Comment by abhikhanna30** [comment]
Hi @shubhtuls, Thank you for clearing that up.

I had another doubt. In the paper section 4. Experiments Implementation details, you mention the for calculating gradient flow, you find the distance field and its derivatives in a dense regular grid.
can you explain this a little bit and point me where in the code you take care of this?

Thanks,
Abhijeet

**Comment by shubhtuls** [comment]
In the [preprocessing script](https://github.com/shubhtuls/volumetricPrimitives/blob/master/preprocess/shapenet/precomputeShapeData.m), we precompute and save the closest mesh point to each grid centre. 

[This function](https://github.com/shubhtuls/volumetricPrimitives/blob/master/data/cadConfigsChamfer.lua#L104-L125) (called from somewhere within the loss computation function), computes the approximate distance field at the given query points.
