### ISSUE TITLE
Question: how do you bias the cuboids to be small?

### ISSUE THREAD

**Issue by HectorAnadon** [shubhtuls/volumetricPrimitives#2]
Hello,

First of all thanks for sharing the code. I have a couple of questions, how do you bias the cuboids to be small in the first step of the learning? Do you clip the output of the network? Also, how does the last layer that predicts the size, probability, translation and rotation of the primitive looks like? What activation functions have you used? Can you point me where can I find it in the code?

Thank you for your help!

**Comment by shubhtuls** [comment]
Hi,
Thanks for the interest in the code.
We set the shape (and existence probability) biases [here](https://github.com/shubhtuls/volumetricPrimitives/blob/master/experiments/cadAutoEncCuboids/primSelTsdfChamfer.lua#L135-L139). The file which has the corresponding prediction layers is [this](https://github.com/shubhtuls/volumetricPrimitives/blob/master/modules/primitives.lua), where functions with the suffix 'Pred' are used to define the various prediction layers. You can search for the variable 'biasTerms' in this file to see how they are used.

Hope this help.

**Comment by shubhtuls** [comment]
Closing the issue. Reopen if some aspects are unclear.
