### ISSUE TITLE
Loss

### ISSUE THREAD

**Issue by shumink** [shubhtuls/volumetricPrimitives#3]
https://github.com/shubhtuls/volumetricPrimitives/blob/f2cbd3f4b14c72adf6632e8ae1710851c57b5e55/experiments/cadAutoEncCuboids/primSelTsdfChamfer.lua#L154
Hi Shubham,

Can you please kindly explain how is the loss defined on this line related to the consistency loss and coverage loss defined in the paper?

Thanks,
Shumin

**Comment by shubhtuls** [comment]
Hi,
Please see the discussion [here](https://github.com/shubhtuls/volumetricPrimitives/issues/1#issuecomment-364107408).

**Comment by shumink** [comment]
Thank you, that helps a lot
