### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by zhenpeiyang** [shubhtuls/volumetricPrimitives#5]
Hi!
Thank you for sharing the code. I am tring to running the demo code, but I found the link for downloading the pretrained model is broken. I wonder could you fix the link? 
Thanks

**Comment by shubhtuls** [comment]
Hi,
Yes, I'm in the process of migrating data and that may take some time. [Here](https://www.dropbox.com/sh/8fabn61kjw5z39x/AABMg1BXZ-mR8_PDEfApa5Z3a?dl=0) is temporary link in the meantime.
