### ISSUE TITLE
Error while running precomputeShapeData

### ISSUE THREAD

**Issue by mansiag** [shubhtuls/volumetricPrimitives#6]
Hi,
I am getting the following error on running precomputeShapeData file.
error: 'extractfield' undefined near line 34 column 34
error: called from
    getFileNamesFromDirectory at line 34 column 20
    precomputeShapeData at line 18 column 16

**Comment by shubhtuls** [comment]
Could you please provide some more details? For e.g.
1) Were there any changes to code (or data) that you made before?
2) The data preprocessing uses parallel threads, which mess up debugging. Please disable that and please print the full error message after that here - maybe that'll help.

**Comment by mansiag** [comment]
The problem is solved. Thanks!.
