### ISSUE TITLE
not found : point_mesh_squared_distance.mexa64

### ISSUE THREAD

**Issue by RanFeng** [shubhtuls/volumetricPrimitives#8]
Great jobs!
your link with point_mesh_squared_distance.mexa64 not found(404)。could you provide a new link with the precompiled version of point_mesh_squared_distance.mexa64? Thank you very much!

And, I compile `compile_gptoolbox_mex_modified` will occur 
``` matlab
>> compile_gptoolbox_mex_modified
警告: This is **VERY** experimental. In principle, this should compile all of the mex functions in this
directory. In practice, users will surely have to adjust paths and flags at the top of this file. 
> In compile_gptoolbox_mex_modified (line 96) 
Hit any key to continue...
警告: 函数或变量 'EIGEN_INC' 无法识别。 
> In compile_gptoolbox_mex_modified (line 133) 
```
how I solve it?

**Comment by shubhtuls** [comment]
Hi,
Please see the dropbox folder linked in [this previous issue](https://github.com/shubhtuls/volumetricPrimitives/issues/5#issuecomment-452372705).

Thanks!
